"""Mappature predefinite lato Python per sorgenti dei template."""

TEMPLATE_SOURCES: dict = {
    'prospettoevoluzionerisultatoammne': {
        'cell_ref': 'D24',
        'expected_label': 'Risultato di amministrazione al 31 dicembre',
        'label_check_cells': ['A24'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'parteaccantonatab': {
        'cell_ref': 'B33',
        'expected_label': 'Totale parte accantonata',
        'label_check_cells': ['A33'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'dicuifcde': {
        'cell_ref': 'B27',
        'expected_label': 'Fondo crediti di dubbia esigibilità al 31/12',
        'label_check_cells': ['A27'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'partevincolatac': {
        'cell_ref': 'B40',
        'expected_label': 'Totale parte vincolata',
        'label_check_cells': ['A40'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'partedestinataagliinvestimentid': {
        'cell_ref': 'B42',
        'expected_label': 'Totale parte destinata agli investimenti',
        'label_check_cells': ['A42'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'partedisponibileeabcd': {
        'cell_ref': 'B43',
        'compute_if_missing': {'base': 'risultatoamministrazionea',
                               'subtract': ['parteaccantonatab',
                                            'partevincolatac',
                                            'partedestinataagliinvestimentid']},
        'expected_label': 'Totale parte disponibile',
        'label_check_cells': ['A43'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'prospettocassa': {
        'cell_ref': 'D17',
        'expected_label': 'Fondo di cassa al 31 dicembre',
        'label_check_cells': ['A17'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'importocassavincolata': {
        'cell_ref': 'D8',
        'year_cell_ref': 'C6',
        'expected_label': 'di cui cassa vincolata',
        'label_check_cells': ['A8'],
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 4,
        'sheet_name_contains': [
            'SEZ. II-GEST. FIN. CASSA',
            'SEZ. II -DATI CASSA',
            'SEZ. II - Dati Cassa',
            'SEZ. II - GEST_FIN. 1',
        ],
        'source_workbook': 'questionario',
        'strict_expected_label': False,
        'table_refs': [
            {'cell_ref': 'D8', 'year_cell_ref': 'D6'},
            {'cell_ref': 'D12', 'year_cell_ref': 'D10'},
            {'cell_ref': 'E64', 'year_cell_ref': 'E62'},
            {'cell_ref': 'D63', 'year_cell_ref': 'D61'},
        ],
    },
    'debitifuoribilancio': {
        'cell_ref': 'P19',
        'expected_label': '4. Sono stati riconosciuti debiti fuori bilancio nel',
        'label_check_cells': ['B19'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_name': 'Sezione preliminare',
        'source_workbook': 'questionario_debiti',
        'strict_expected_label': False,
    },
    'fcdeinrapportoaresiduiattivi': {
        'cell_ref': 'I6',
        'expected_label': 'FCDE IN RAPPORTO A RESIDUI ATTIVI',
        'label_check_cells': ['B6'],
        'optional': True,
        'source_workbook': 'analysis',
        'is_percentage': False,
        'sheet_name_contains': 'FCDE',
        'strict_expected_label': False,
    },
    'fpvpartecorrenteal3112': {
        'cell_ref': 'D21',
        'expected_label': 'Fondo pluriennale vincolato per spese correnti',
        'label_check_cells': ['A21'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': True,
    },
    'fpvpartecapitaleal3112': {
        'cell_ref': 'D22',
        'expected_label': 'Fondo pluriennale vincolato per spese in conto capitale',
        'label_check_cells': ['A22'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': True,
    },
    'fondocontenzioso': {
        'cell_ref': 'I16',
        'expected_label': ['Totale Fondo contenzioso'],
        'label_check_cells': ['B16'],
        'default_if_missing': 0,
        'only_fill_if_found': True,
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '12',
        'source_workbook': 'rendiconto',
        'static_column': True,
        'strict_expected_label': True,
    },
    'potenzialipassivita': {
        'cell_ref': 'I26',
        'expected_label': ['FONDO ACCANTONAMENTO PASSIVITA POTENZIALI'],
        'label_check_cells': ['D26'],
        'default_if_missing': 0,
        'only_fill_if_found': True,
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '12',
        'source_workbook': 'rendiconto',
        'static_column': True,
        'strict_expected_label': True,
    },
    'fondogaranziadebiticommerciali': {
        'cell_ref': 'I23',
        'expected_label': 'Totale Fondo di garanzia debiti commerciali',
        'label_check_cells': ['B23'],
        'only_fill_if_found': True,
        'optional': True,
        'row_tolerance': 5,
        'sheet_idx': '12',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'fondivincolaticovid': {
        'expected_label': 'TRASFERIMENTI CORRENTI DA PRESIDENZA DEL CONSIGLIO DEI MINISTI -ORDINANZA ' \
                          'PROTEZIONE CIVILE N. 658 DEL 29.03.2020 -EMERGENZA SANITARIA LEGATA AL ' \
                          'DIFFONDERSI DEL CIRUS COVID-19 - MISURE URGENTI DI SOLIDARIETA ALIMENTARE',
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '13',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
        'sum_cells': ['O'],
    },
    'rispettoequilibri': {
        'cell_ref': 'B69',
        'expected_label': 'W1) Risultato di competenza',
        'search_key_prefix': 'W1)',
        'label_check_cells': ['A69'],
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '7',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'equilibriodibilanciow2': {
        'cell_ref': 'B72',
        'expected_label': 'W2) Equilibrio di bilancio',
        'search_key_prefix': 'W2)',
        'label_check_cells': ['A81'],
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '7',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'equilibriocomplessivow3': {
        'cell_ref': 'B74',
        'expected_label': 'W3) Equilibrio complessivo',
        'search_key_prefix': 'W3)',
        'label_check_cells': ['A83'],
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '7',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'fondocassadaidatisiope': {
        'row_tolerance': 2.0,
    },
    'anticipazionetesoreria': {
        'expected_label': 'Titolo 7: Anticipazioni da istituto tesoriere/cassiere',
        'label_check_cells': ['A31'],
        'cell_refs': ['B31'],
        'optional': True,
        'row_tolerance': 10,  
        'sheet_idx': '6',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'fal': {
        'cell_ref': 'B29',
        'expected_label': 'Fondo anticipazioni liquidità',
        'label_check_cells': ['A29'],
        'optional': True,
        'row_tolerance': 10,
        'sheet_idx': '11',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'contrazionenuovimutui': {
        'cell_ref': 'E25',
        'fallback_cell_refs': ['F25'],
        'expected_label': '3) Debito complessivo contratto',
        'label_check_cells': ['A25', 'A25:C25'],
        'optional': True,
        'row_tolerance': 10,
        'sheet_name_contains': 'SEZ. IV -INDEBITAMENTO_DATI _',
        'source_workbook': 'questionario',
        'strict_expected_label': False,
        'static_column': True,
        'check_year_in_label': True
    },
    'accantonamentocifrarelativaairinnovicontrattualidelccnl': {
        'cell_ref': 'I26',
        'expected_label': 'FONDO RINNOVI CONTRATTUALI',
        'label_check_cells': ['D26'],
        'optional': True,
        'row_tolerance': 3,
        'sheet_idx': '12',
        'source_workbook': 'rendiconto',
        'strict_expected_label': False,
    },
    'spesadelpersonalesostenuta': {
        'source_workbook': 'relazione',
        'row_tolerance': 2.0,
    },
    'incidenzaspesapersonalesuspesacorrente': {
        'cell_ref': 'D27',
        'expected_label': 'Incidenza della spesa di personale sulla spesa corrente',
        'label_check_cells': ['B27'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '1',
        'source_workbook': 'indicatori',
        'strict_expected_label': False,
    },
    '%riscossionisanzionidelcodicedellastrada': {
        'cell_ref': 'C20',
        'year_cell_ref': 'E5',
        'expected_label': 'Percentuale di riscossione',
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 0,
        'sheet_name_contains': [
            'SEZ. II- DATI ENTRATE',
            'SEZ. II - DATI ENTRATE',
            'SEZ. II-DATI ENTRATE',
            'SEZ. II- Gest. ENTRATE',
            'SEZ. II - GEST. ENTRATE',
        ],
        'source_workbook': 'questionario',
        'strict_expected_label': False,
        'table_refs': [
            {'cell_ref': 'C20', 'year_cell_ref': 'E5'},
            {'cell_ref': 'C24', 'year_cell_ref': 'D15'},
            {'cell_ref': 'D25', 'year_cell_ref': 'E16'},
            {'cell_ref': 'B32', 'year_cell_ref': 'C23'},
        ],
        'is_percentage': True,
    },
    '%riscossioniproventidapermessoacostruire': {
        'source_workbook': 'relazione',
        'row_tolerance': 2.0,
        'is_percentage': True,
    },
    'contrastoallevasionetributaria': {
        'source_workbook': 'questionario',
        'row_tolerance': 2.0,
    },
    '%diriscossionecomplessiva': {
        'row_tolerance': 2.0,
        'is_percentage': True,
    },
    'residuiattivifcde_titolo_uno': {
        'cell_ref': 'D19',
        'expected_label': 'Totale Titolo 1: Entrate correnti di natura tributaria, contributiva e perequativa',
        'label_check_cells': ['B19'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '16',
        'source_workbook': 'rendiconto'
    },
    'residuiattivifcde_titolo_tre': {
        'cell_ref': 'D35',
        'expected_label': 'Totale Titolo 3: Entrate extratributarie',
        'label_check_cells': ['B35'],
        'optional': True,
        'row_tolerance': 2,
        'sheet_idx': '16',
        'source_workbook': 'rendiconto'
    },
    'residuiattividatatiprecedenti2021_titolo_uno': {
        'cell_ref': 'C71',
        'display_refs': [('TITOLO I', 'C71')],
        'fallback_display_refs': [
            {
                'title': 'TITOLO I',
                'cell_ref': 'F6',
                'expected_label': 'Entrate Titolo 1.00',
                'label_check_cells': ['B6'],
                'row_tolerance': 2,
                'sheet_name_contains': ['SEZ. II - Dati Cassa', 'SEZ. II -DATI CASSA', 'SEZ. II-DATI CASSA'],
            },
        ],
        'year_cell_ref': ['C69','D69', 'E69', 'F69', 'G69'],
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 2,
        'sheet_name_contains': 'SEZ. II -DATI RISULT. FINAN',
        'source_workbook': 'questionario',
        'strict_expected_label': False,
    },
    'residuiattividatatiprecedenti2021_titolo_tre': {
        'cell_ref': 'C73',
        'display_refs': [('TITOLO III', 'C73')],
        'fallback_display_refs': [
            {
                'title': 'TITOLO III',
                'cell_ref': 'F10',
                'expected_label': 'Entrate Titolo 3.00',
                'label_check_cells': ['B10'],
                'row_tolerance': 2,
                'sheet_name_contains': ['SEZ. II - Dati Cassa', 'SEZ. II -DATI CASSA', 'SEZ. II-DATI CASSA'],
            },
        ],
        'year_cell_ref': ['C69','D69', 'E69', 'F69', 'G69'],
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 2,
        'sheet_name_contains': 'SEZ. II -DATI RISULT. FINAN',
        'source_workbook': 'questionario',
        'strict_expected_label': False,
    },
    'residuiattividatatiprecedenti2021_titolo_quattro': {
        'cell_ref': 'C74',
        'display_refs': [('TITOLO IV', 'C74')],
        'fallback_display_refs': [
            {
                'title': 'TITOLO IV',
                'cell_ref': 'F12',
                'expected_label': 'Entrate Titolo 4.02.06',
                'label_check_cells': ['B12'],
                'row_tolerance': 2,
                'sheet_name_contains': ['SEZ. II - Dati Cassa', 'SEZ. II -DATI CASSA', 'SEZ. II-DATI CASSA'],
            },
        ],
        'year_cell_ref': ['C69','D69', 'E69', 'F69', 'G69'],
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 2,
        'sheet_name_contains': 'SEZ. II -DATI RISULT. FINAN',
        'source_workbook': 'questionario',
        'strict_expected_label': False,
    },
    'residuipassividatati': {
        'cell_ref': 'C83',
        'display_refs': [('TITOLO I', 'C83')],
        'fallback_display_refs': [
            {
                'title': 'TITOLO I',
                'cell_ref': 'F15',
                'expected_label': 'Spese Titolo 1.00 - Spese correnti',
                'label_check_cells': ['B15'],
                'row_tolerance': 2,
                'sheet_name_contains': ['SEZ. II - Dati Cassa', 'SEZ. II -DATI CASSA', 'SEZ. II-DATI CASSA'],
            },
        ],
        'year_cell_ref': ['C81', 'D81', 'E81', 'F81', 'G81'],
        'optional': True,
        'prefer_exact_table_workbook': True,
        'row_tolerance': 4,
        'sheet_name_contains': 'SEZ. II -DATI RISULT. FINAN',
        'source_workbook': 'questionario',
        'strict_expected_label': False,
    },
    'disavanzodariaccertamentostraordinario': {
        'source_workbook': 'questionario',
    },
    'controllosullesocietàpartecipate': {
        'source_workbook': 'questionario',
    },
    'partenariatopubblicoprivato': {
        'source_workbook': 'questionario',
    },
    'prospettocoperturaserviziadomanda': {
        'source_workbook': 'questionario',
    },
    'resacontoagenti': {
        'source_workbook': 'questionario',
    },
}
